### ISSUE TITLE
Write tests for your code

### ISSUE THREAD

**Issue by Stepandanci** [butnaru1/TestTask#6]
You wrote good test task but you can update it.

Your last task to write tests.
Read about a framework for tests Rspec https://rspec.info, https://habr.com/ru/post/53264/

Include all code of `VictoriaBankFinalBeta.rb` in 1 class.
Divide the code into specific methods.
Separate methods for fetch HTML and for parse it.

An example structure of your class

```ruby
class VictoriaBank

  def input_credentials

  end

  def connect

  end

  def fetch_accounts
    # go to accounts HTML
    parse_accounts(Nokogiri::HTML(browser.html))
  end

  def fetch_transactions
    # go to transactions HTML
    # add transactions to account
    parse_transactions(account, Nokogiri::HTML(browser.html))
  end

  def parse_accounts(html)
    # add accounts here
  end

  def parse_transactions(account, html)
    # add transactions here
  end
end
```

In VictoriaBank_spec.rb file describe class VictoriaBank
and write specs for parse_accounts and parse_transactions
save 2 HTML files and show parsing results.

Create new files VictoriaBank.rb and VictoriaBank_spec.rb
Open new merge request.

Good luck.

**Comment by butnaru1** [comment]
I have one question. 
All methods need to work independent?
For example: 
obj = VictoriaBank.new
obj.fetch_accounts
In this case fech_accounts have to call input_credentials and connect or not?

**Comment by Stepandanci** [comment]
The main issue is to test your 2 parsing methods (parse_accounts and parse_transactions).

You need to separate these 2 methods and save 2 HTML files. 
Test 1 example of account and transaction.

Create methods how you want. 
You can write input credentials in the connect or separate in.

For easy to read your code put all methods in the `execute` method.

```ruby
class VictoriaBank
  def execute
    connect
    fetch_accounts
    fetch_transactions
    print_result
  end

  def fetch_accounts
    @accounts = []
    # go to accounts HTML
    # add accounts here
    parse_accounts(Nokogiri::HTML(browser.html))
  end

 def fetch_transactions
  @accounts.each do |account|
    # go to transactions HTML
    # add transactions to account
    parse_transactions(account, Nokogiri::HTML(browser.html))
  end
end

# call methods how you want
object = VictoriaBank.new
object.execute
```

In VictoriaBank_spec, you need to describe VictoriaBank.
Test `parse_accounts` and `parse_transactions`.

**Comment by Stepandanci** [comment]
If you have any questions, I answer you today.

**Comment by butnaru1** [comment]
> 
> 
> If you have any questions, I answer you today.

I made some changes. If you can look if I am on right way.

**Comment by Stepandanci** [comment]
You should show an example of 
- account data (name, balance, currency, nature).
- transaction data (date, description, amount, currency, account_name).

you have the method `to_json` for these.

**Comment by butnaru1** [comment]
When you say show, you mean that I will copy the result of  and show it or to apply JSON method like:
victoriabank = VictoriaBank.new
    puts JSON.pretty_generate victoriabank.parse_accounts("#{File.open('Cards and accounts.html').read}")

**Comment by Stepandanci** [comment]
You should read about Rspec  
https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers

a code example:
```ruby
html     = File.open('accounts.html').read
accounts = victoriabank.parse_accounts(html)
result   = accounts[0].to_json

expect(result).to eq(
  {
    "name"      => "MD123456",
    "balance"   => 0.0,
    "currency"  => "USD"
  }
)
```

**Comment by butnaru1** [comment]
I hope that I understood correctly.

**Comment by Stepandanci** [comment]
Congratulations to you!
You have completed all points of your test task.
We will contact you on Monday.
Do not merge your pull request yet.

**Comment by butnaru1** [comment]
Thank You!
